services:
  web:
    image: app-name:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

