name: Deploy Laravel Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel on EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} << 'EOF'
        cd /var/www/html/FSD-Laravel
        git pull origin main
        docker-compose down
        docker-compose build
        docker-compose up -d
        docker exec fsd-laravel-web-1 php artisan migrate --force
        docker exec fsd-laravel-web-1php artisan key:generate
        docker exec fsd-laravel-web-1 php artisan config:clear
        docker exec fsd-laravel-web-1 php artisan cache:clear
        docker exec fsd-laravel-web-1 php artisan route:clear
        docker exec fsd-laravel-web-1 chown -R www-data:www-data /var/www/html/storage
        docker exec fsd-laravel-web-1 chmod -R 775 /var/www/html/storage
        EOF
