name: Deploy Laravel Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel on EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} << 'EOF'
        cd /var/www/html
        git pull origin main
        docker-compose down
        docker-compose build
        docker-compose up -d
        docker exec laravel-app php artisan migrate --force
        docker exec laravel-app php artisan config:clear
        docker exec laravel-app php artisan cache:clear
        EOF
